import { Html, Head, Main, NextScript } from 'next/document';

const Document = (): JSX.Element => (
	<Html>
		<Head>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
			<link
				href='https://fonts.googleapis.com/css2?family=Hubballi'
				rel='stylesheet'
			/>
		</Head>
		<body>
			<Main />
			<NextScript />
		</body>
	</Html>
);

export default Document;
