import type { NextPage } from 'next'
import Head from 'next/head'

import SplashButton from '../components/SplashButton'

const Home: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Spacebook</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=Hubballi" rel="stylesheet" />
        </Head>

        <main className='font-body h-screen'>
          <header className='flex justify-center items-center bg-slate py-1 px-4'>
            <img src='/Logo.svg' alt='Logo'/>
          </header>

          <div className='flex flex-col justify-start items-center gap-4 h-full mt-[15%]'>
            <SplashButton
              text='Login'
              onClick={() => console.log('Login')}
            />
            <SplashButton
              text='Signup'
              onClick={() => console.log('Signup')}
            />
          </div>
        </main>
      </div>
    )
  }

  export default Home