import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Create Test App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1 className="text-3xl font-bold underline">
            Hello Test!
          </h1>
          <button className='bg-blue-500 text-white font-bold py-2 px-4 rounded'>Test Button</button>
        </main>
      </div>
    )
  }

  export default Home